In [2]:
import osmnx as ox
import matplotlib.pyplot as plt

In [41]:
place_name = ['Moscow', 'Moscow Oblast']
tags = {'railway': 'station', 'railway': 'halt'}
stations = ox.geometries_from_place(place_name, tags)
stations.head()

                        esr:user express:user               name old_name  \
element_type osmid
node         1232338305   228826      2000491             Мягкое   162 км
             1232338310   228953      2002011             152 км      NaN
             1232342044   228718      2000096         Кораблёвка      NaN
             1232342049   228811      2000637  Дудино-Серебряное      NaN
             1915811736   229142          NaN            Клёмово      NaN

                        railway  uic_ref                   geometry   name:en  \
element_type osmid
node         1232338305    halt  2000491  POINT (38.64705 54.49617)       NaN
             1232338310    halt      NaN  POINT (38.61035 54.58590)    152 km
             1232342044    halt  2000096  POINT (38.76764 54.39573)       NaN
             1232342049    halt  2000637  POINT (38.66465 54.47821)       NaN
             1915811736    halt  2000467  POINT (38.74723 54.53911)  Klyomovo

                           wikidata public_transport  ... lang:en image  \
element_type osmid                                    ...
node         1232338305         NaN              NaN  ...     NaN   NaN
             1232338310  Q104363314              NaN  ...     NaN   NaN
             1232342044         NaN              NaN  ...     NaN   NaN
             1232342049         NaN              NaN  ...     NaN   NaN
             1915811736    Q4223296              NaN  ...     NaN   NaN

                        name:fr note:1 name:alt esr:user_1 addr:country nodes  \
element_type osmid
node         1232338305     NaN    NaN      NaN        NaN          NaN   NaN
             1232338310     NaN    NaN      NaN        NaN          NaN   NaN
             1232342044     NaN    NaN      NaN        NaN          NaN   NaN
             1232342049     NaN    NaN      NaN        NaN          NaN   NaN
             1915811736     NaN    NaN      NaN        NaN          NaN   NaN

                        building internet_access
element_type osmid
node         1232338305      NaN             NaN
             1232338310      NaN             NaN
             1232342044      NaN             NaN
             1232342049      NaN             NaN
             1915811736      NaN             NaN

[5 rows x 55 columns]

In [42]:
import pandas as pd

st = pd.DataFrame(data=stations,columns=['express:user','name', 'geometry'])

In [59]:
st.reset_index().to_csv('stations.csv',sep=',')